name: Publish

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ vars.RELEASE_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.RELEASE_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.RELEASE_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.RELEASE_COMMITTER_EMAIL }}

  update-next:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [release]
    name: Update next
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'next'
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}

      - name: Back-merge master into next
        run: |
          git merge --ff-only origin/master
          git push
