name: Publish

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

  update-next:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [release]
    name: Update next
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'next'
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}

      - name: Back-merge master into next
        run: |
          git merge --ff-only origin/master
          git push
